import {
  Bath,
  BookOpenText,
  BriefcaseBusiness,
  BrushCleaning,
  Bus,
  Car,
  ChartColumnIncreasing,
  ChefHat,
  ChessKnight,
  Church,
  Cone,
  Flower2,
  GraduationCap,
  Guitar,
  Hamburger,
  Headphones,
  Landmark,
  Laptop,
  Mail,
  NotebookPen,
  Paintbrush,
  PhoneCall,
  Plane,
  Rocket,
  Sofa,
  Soup,
  Telescope,
  TestTubeDiagonal,
  TreePine,
  Wrench,
} from 'lucide-react';

export const iconOptions = [
  { name: 'Laptop', icon: Laptop },
  { name: 'BookOpenText', icon: BookOpenText },
  { name: 'TreePine', icon: TreePine },
  { name: 'Plane', icon: Plane },
  { name: 'Hamburger', icon: Hamburger },
  { name: 'Bath', icon: Bath },
  { name: 'BriefcaseBusiness', icon: BriefcaseBusiness },
  { name: 'BrushCleaning', icon: BrushCleaning },
  { name: 'Bus', icon: Bus },
  { name: 'Car', icon: Car },
  { name: 'ChartColumnIncreasing', icon: ChartColumnIncreasing },
  { name: 'ChefHat', icon: ChefHat },
  { name: 'ChessKnight', icon: ChessKnight },
  { name: 'Church', icon: Church },
  { name: 'Cone', icon: Cone },
  { name: 'Flower2', icon: Flower2 },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Guitar', icon: Guitar },
  { name: 'Headphones', icon: Headphones },
  { name: 'Landmark', icon: Landmark },
  { name: 'Mail', icon: Mail },
  { name: 'NotebookPen', icon: NotebookPen },
  { name: 'Paintbrush', icon: Paintbrush },
  { name: 'PhoneCall', icon: PhoneCall },
  { name: 'Rocket', icon: Rocket },
  { name: 'Soup', icon: Soup },
  { name: 'Sofa', icon: Sofa },
  { name: 'Telescope', icon: Telescope },
  { name: 'TestTubeDiagonal', icon: TestTubeDiagonal },
  { name: 'Wrench', icon: Wrench },
];

export const colorOptions = [
  {
    name: 'Emerald Green',
    bgColor: 'bg-emerald-500',
    textColor: 'text-emerald-500',
    focusColor: 'focus:bg-emerald-500/70',
  },
  {
    name: 'Modern Cyan',
    bgColor: 'bg-cyan-400',
    textColor: 'text-cyan-400',
    focusColor: 'focus:bg-cyan-400/70',
  },
  {
    name: 'Deep Sky Blue',
    bgColor: 'bg-sky-500',
    textColor: 'text-sky-500',
    focusColor: 'focus:bg-sky-500/70',
  },
  {
    name: 'Pastel Brown',
    bgColor: 'bg-stone-400',
    textColor: 'text-stone-400',
    focusColor: 'focus:bg-stone-400/70',
  },
  {
    name: 'Midnight black',
    bgColor: 'bg-slate-300',
    textColor: 'text-slate-300',
    focusColor: 'focus:bg-slate-300/70',
  },
  {
    name: 'Apple Red',
    bgColor: 'bg-red-500',
    textColor: 'text-red-500',
    focusColor: 'focus:bg-red-500/70',
  },
  {
    name: 'French Rose',
    bgColor: 'bg-pink-500',
    textColor: 'text-pink-500',
    focusColor: 'focus:bg-pink-500/70',
  },
  {
    name: 'Coral Pink',
    bgColor: 'bg-rose-400',
    textColor: 'text-rose-400',
    focusColor: 'focus:bg-rose-400/70',
  },
  {
    name: 'Bright Orange',
    bgColor: 'bg-amber-500',
    textColor: 'text-amber-500',
    focusColor: 'focus:bg-amber-500/70',
  },
  {
    name: 'Soft Violet',
    bgColor: 'bg-violet-400',
    textColor: 'text-violet-400',
    focusColor: 'focus:bg-violet-400/70',
  },
  {
    name: 'Neon Indigo',
    bgColor: 'bg-indigo-400',
    textColor: 'text-indigo-400',
    focusColor: 'focus:bg-indigo-400/70',
  },
  {
    name: 'Electric Yellow',
    bgColor: 'bg-yellow-400',
    textColor: 'text-yellow-400',
    focusColor: 'focus:bg-yellow-400/70',
  },
];
